# Generated by Django 4.2.11 on 2024-09-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fg',
            name='prev_submit_serial',
            field=models.BooleanField(default=False),
        ),
    ]
