# Generated by Django 4.2.11 on 2024-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0002_fg_prev_submit_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fg',
            name='prev_submit_serial',
        ),
        migrations.AddField(
            model_name='dummy',
            name='pdf_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fg',
            name='pdf_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
