# Generated by Django 4.2.11 on 2024-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0003_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fg',
            name='prev_submit',
            field=models.BooleanField(default=False),
        ),
    ]
